USE [master]
GO

/****** Object:  Database [DB_x]    Script Date: 2018/10/23 21:44:10 ******/
CREATE DATABASE [DB_x]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_x', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DB_x.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_x_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DB_x_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [DB_x] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_x].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_x] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_x] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_x] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_x] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_x] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_x] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_x] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_x] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_x] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_x] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_x] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_x] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_x] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_x] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_x] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_x] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_x] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_x] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_x] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_x] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_x] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_x] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_x] SET RECOVERY FULL 
GO

ALTER DATABASE [DB_x] SET  MULTI_USER 
GO

ALTER DATABASE [DB_x] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_x] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_x] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_x] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DB_x] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_x] SET QUERY_STORE = OFF
GO

USE [DB_x]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [DB_x] SET  READ_WRITE 
GO

